//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Riolu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project_Riolu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to —
        ///Stench
        ///Drizzle
        ///Speed Boost
        ///Battle Armor
        ///Sturdy
        ///Damp
        ///Limber
        ///Sand Veil
        ///Static
        ///Volt Absorb
        ///Water Absorb
        ///Oblivious
        ///Cloud Nine
        ///Compound Eyes
        ///Insomnia
        ///Color Change
        ///Immunity
        ///Flash Fire
        ///Shield Dust
        ///Own Tempo
        ///Suction Cups
        ///Intimidate
        ///Shadow Tag
        ///Rough Skin
        ///Wonder Guard
        ///Levitate
        ///Effect Spore
        ///Synchronize
        ///Clear Body
        ///Natural Cure
        ///Lightning Rod
        ///Serene Grace
        ///Swift Swim
        ///Chlorophyll
        ///Illuminate
        ///Trace
        ///Huge Power
        ///Poison Point
        ///Inner Focus
        ///Magma Armor
        ///Water Veil
        ///Magnet Pull
        ///Soundproof
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Abilities {
            get {
                return ResourceManager.GetString("Abilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None
        ///Master Ball
        ///Ultra Ball
        ///Great Ball
        ///Poké Ball
        ///Safari Ball
        ///Net Ball
        ///Dive Ball
        ///Nest Ball
        ///Repeat Ball
        ///Timer Ball
        ///Luxury Ball
        ///Premier Ball
        ///Dusk Ball
        ///Heal Ball
        ///Quick Ball
        ///Cherish Ball
        ///Potion
        ///Antidote
        ///Burn Heal
        ///Ice Heal
        ///Awakening
        ///Paralyze Heal
        ///Full Restore
        ///Max Potion
        ///Hyper Potion
        ///Super Potion
        ///Full Heal
        ///Revive
        ///Max Revive
        ///Fresh Water
        ///Soda Pop
        ///Lemonade
        ///Moomoo Milk
        ///Energy Powder
        ///Energy Root
        ///Heal Powder
        ///Revival Herb
        ///Ether
        ///Max Ether
        ///Elixir
        ///Max Elixir
        ///Lava Cookie
        ///Berry Juice [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ———
        ///Pound
        ///Karate Chop
        ///Double Slap
        ///Comet Punch
        ///Mega Punch
        ///Pay Day
        ///Fire Punch
        ///Ice Punch
        ///Thunder Punch
        ///Scratch
        ///Vice Grip
        ///Guillotine
        ///Razor Wind
        ///Swords Dance
        ///Cut
        ///Gust
        ///Wing Attack
        ///Whirlwind
        ///Fly
        ///Bind
        ///Slam
        ///Vine Whip
        ///Stomp
        ///Double Kick
        ///Mega Kick
        ///Jump Kick
        ///Rolling Kick
        ///Sand Attack
        ///Headbutt
        ///Horn Attack
        ///Fury Attack
        ///Horn Drill
        ///Tackle
        ///Body Slam
        ///Wrap
        ///Take Down
        ///Thrash
        ///Double-Edge
        ///Tail Whip
        ///Poison Sting
        ///Twineedle
        ///Pin Missile
        ///Leer
        ///Bite
        ///Growl
        ///Roar
        ///Sing
        ///Supersonic
        ///Sonic Boom
        ///Dis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Moves {
            get {
                return ResourceManager.GetString("Moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardy
        ///Lonely
        ///Brave
        ///Adamant
        ///Naughty
        ///Bold
        ///Docile
        ///Relaxed
        ///Impish
        ///Lax
        ///Timid
        ///Hasty
        ///Serious
        ///Jolly
        ///Naive
        ///Modest
        ///Mild
        ///Quiet
        ///Bashful
        ///Rash
        ///Calm
        ///Gentle
        ///Sassy
        ///Careful
        ///Quirky.
        /// </summary>
        internal static string Natures {
            get {
                return ResourceManager.GetString("Natures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egg
        ///Bulbasaur
        ///Ivysaur
        ///Venusaur
        ///Charmander
        ///Charmeleon
        ///Charizard
        ///Squirtle
        ///Wartortle
        ///Blastoise
        ///Caterpie
        ///Metapod
        ///Butterfree
        ///Weedle
        ///Kakuna
        ///Beedrill
        ///Pidgey
        ///Pidgeotto
        ///Pidgeot
        ///Rattata
        ///Raticate
        ///Spearow
        ///Fearow
        ///Ekans
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandshrew
        ///Sandslash
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Clefairy
        ///Clefable
        ///Vulpix
        ///Ninetales
        ///Jigglypuff
        ///Wigglytuff
        ///Zubat
        ///Golbat
        ///Oddish
        ///Gloom
        ///Vileplume
        ///Paras
        ///Parasect
        ///Venonat
        ///Venomoth
        ///Diglett
        ///Dugtrio
        ///Meowth
        ///Persian
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Species {
            get {
                return ResourceManager.GetString("Species", resourceCulture);
            }
        }
    }
}
